import 'dart:async';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:eva_icons_flutter/eva_icons_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:flutter_svg/svg.dart';
import 'package:get/get.dart';
import 'package:iconly/iconly.dart';
import 'package:iconsax/iconsax.dart';
import "package:intl/intl.dart" hide TextDirection;
import 'package:loading_indicator/loading_indicator.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';

import '../../controllers/controllers.dart';
import '../../extensions/extensions.dart';
import '../../models/custom_data_theme.dart';
import '../../models/custom_item_drawer_setting.dart';
import '../../models/custom_item_dropdown.dart';
import '../../models/custom_item_menu.dart';
import '../../models/custom_item_navbar.dart';
import '../../models/custom_item_text.dart';
import '../../shared/shared.dart';
import '../../routes/routes.dart';

part 'custom_appbar_widget.dart';
part 'custom_button_widget.dart';
part 'custom_cache_image.dart';
part 'custom_card_widget.dart';
part 'custom_clipper_widget.dart';
part 'custom_divider_widget.dart';
part 'custom_drawer_settings_widget.dart';
part 'custom_dropdown_widget.dart';
part 'custom_generic_widget.dart';
part 'custom_masonry_widget.dart';
part 'custom_navbar_widget.dart';
part 'custom_padding_widget.dart';
part 'custom_radio_widget.dart';
part 'custom_responsive_widget.dart';
part 'custom_scroll_modifier.dart';
part 'custom_text_field.dart';
part 'custom_text_input_formatter.dart';
part 'custom_text_widget.dart';
